# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      additional_dependencies: [pep8-naming, flake8_import_order, flake8_docstrings, flake8_comprehensions, flake8_bugbear, flake8_annotations, flake8_simplify]
      exclude: examples/
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  -   id: mypy
      args: [--ignore-missing-imports]
      exclude: examples/
      additional_dependencies: [types-toml]
