from typing import Any, Type, Optional, List
from pydantic import BaseModel, create_model
from pydantic_core import PydanticUndefined
import dataclasses

from semantix import Semantic, enhance
from semantix.llms import OpenAI

llm = OpenAI(max_tokens=2048)


def pydantic_to_dataclass(
    klass: Type[BaseModel],
    classname: str = None,
) -> Any:
    """
    Dataclass from Pydantic model

    Transferred entities:
        * Field names
        * Type annotations, except of Annotated etc
        * Default factory or default value

    Validators are not transferred.

    Order of fields may change due to dataclass's positional arguments.

    """
    # https://stackoverflow.com/questions/78327471/how-to-convert-pydantic-model-to-python-dataclass
    dataclass_args = []
    for name, info in klass.model_fields.items():
        if info.default_factory is not None:
            dataclass_field = dataclasses.field(
                default_factory=info.default_factory,
            )
            dataclass_arg = (name, info.annotation, dataclass_field)
        elif info.default is not PydanticUndefined:
            dataclass_field = dataclasses.field(
                default=info.get_default(),
            )
            dataclass_arg = (name, info.annotation, dataclass_field)
        else:
            dataclass_arg = (name, info.annotation)
        dataclass_args.append(dataclass_arg)
    dataclass_args.sort(key=lambda arg: len(arg) > 2)
    return dataclasses.make_dataclass(
        classname or f"{klass.__name__}",
        dataclass_args,
    )


ner_entities = [
    "passport_number",
    "bank_routing_number",
    "account_pin",
    "swift_bic_code",
    "password",
    "credit_card_number",
    "email",
    "phone_number",
    "person_name",
    "iban",
    "ipv6",
    "api_key",
    "street_address",
    "company",
    "local_latlng",
    "time",
    "employee_id",
    "customer_id",
    "date_of_birth",
    "ipv4",
    "bban",
]

NER = pydantic_to_dataclass(
    create_model("NER", **{name: (Optional[List[str]], None) for name in ner_entities})
)
NER.__doc__ = "The named entities present in the text"


@enhance("Extract named entities from the given text", llm)
def extract_entities(text: str) -> Semantic[NER, "Named Entities"]:  # type: ignore
    """Only use the given entities. Do not made up new entities."""


texts = [
    "**Loan Application Form**\n\n**Applicant Information**\n\nFull Name: Nicolas Dobes\n\nDate of Birth: 14/05/1969\n\n**Contact Information**\n\nStreet Address: Flat 2, Gareth Ridge\n\n**Loan Information**\n\nLoan Amount: £100,000\n\nPurpose of Loan: Business Expansion\n\n**Collateral Assessment**\n\n1. **Real Estate:**\n   - Property Address: 2 Gareth Ridge, Apartment 2\n   - Property Type: Residential Apartment\n  ",
    "---\nHealth Insurance Claim Form\n\nPatient Information:\nName: Jann N. Butte\nAddress: 85904 Kara Pike\nLocal Latitude-Longitude: 60.273727, 119.642490\n\nHealthcare Provider Information:\nDentist Name: Smiling Seas Dental\nAddress: 346 Sunshine Ave, Anytown, CA 94123\n\nTreatment Information:\nDate of Service: 01/15/2023\n\nDescription of Treatment:\nPatient, Jann N. Butte, received a dental cleaning and two fillings for cavities on 01/15/2023 at Smiling Seas Dental. The dental cleaning was a routine procedure, while the fillings were necessary to address tooth decay. The total cost of the treatment was $350.\n\nTreatment Details:\n- Dental Cleaning: $100\n- Filling (Tooth 1): $125\n- Filling (Tooth 2): $125\n\nTotal Amount Claimed: $350\n\nSignature: Jann N. Butte\nDate: 01/18/2023\n\n---",
    '"StudentID","Name","Age","Gender","Grade","Subject","Score","SchoolName","SchoolLocation"\n"1","John Doe","15","Male","10","Math","92","Maplewood High School","Oakland, CA"\n"2","Jane Smith","16","Female","11","English","88","Maplewood High School","Oakland, CA"\n"3","Alice Johnson","15","Female","10","Science","95","Maplewood High School","Oakland, CA"\n"4","Bob Brown","16","Male","11","History","85","Maplewood High School","Oakland, CA"\n"5","Charlie Davis","15","Male","10","Math","89","Maplewood High School","Oakland, CA"\n"6","Emily Wilson","16","Female","11","English","92","Maplewood High School","Oakland, CA"\n"7","Frank Garcia","15","Male","10","Science","98","Maplewood High School","Oakland, CA"\n"8","Grace Miller","16","Female","11","History","88","Maplewood High School","Oakland, CA"\n"9","Harry Thompson","15","Male","10","Math","75","Maplewood High School","Oakland, CA"\n"10","Jessica Moore","16","Female","11","English","90","Maplewood High School","Oakland, CA"\n"11","James Taylor","15","Male","10","Science","89","Maplewood High School","Oakland, CA"\n"12","Karen Clark","16","Female","11","History","95","Maplewood High School","Oakland, CA"\n"13","Larry White","15","Male","10","Math","78","Maplewood High School","Oakland, CA"\n"14","Mia Green","16","Female","11","English","85","',
    "**Acme Insurance Policyholder's Emergency Preparedness Guide**\n\nDear Policyholder,\n\nWe hope this guide finds you well. At Acme Insurance, we take our commitment to your safety and security seriously. As part of our commitment, we are pleased to provide you with this personalized Emergency Preparedness Guide. This guide is designed to help you prepare for and respond to various types of emergencies and disasters.\n\n**Policy Information**\n\nPolicy Status: Active\nPolicy Number: 123456789\nPremium Due: $500, due on June 1, 2023\nCoverage Details: Comprehensive coverage, including fire, theft, and natural disasters\n\n**Emergency Preparedness Guide**\n\nAt Acme Insurance, we understand that emergency preparedness is crucial for the safety and well-being of you and your loved ones. That's why we have put together this comprehensive guide, complete with personalized recommendations based on your policyholder location and potential risks.\n\n**1. Create an Emergency Plan**\n\n* Identify the types of emergencies that are most likely to occur in your area, such as floods, earthquakes, or hurricanes.\n* Develop a family emergency plan that includes evacuation routes, communication plans, and meeting locations.\n* Ensure that all family members are familiar with the plan and know what to do in case of an emergency.\n\n**2. Build an Emergency Kit**\n\n* Assemble a well-stocked emergency kit that includes essentials such as water, non-perishable food, first aid supplies, flashlights, batteries, a battery-powered or hand-crank radio, and personal hygiene items.\n* Store your emergency kit in a easily accessible location, such as a hall closet or garage.\n\n**3. Secure Your Home**\n\n* Install smoke detectors on every level of your home and test them monthly.\n* Ensure that your home has a working carbon monoxide detector.\n* Secure heavy items, such as bookshelves and televisions, to the wall to prevent them from falling during an earthquake or high winds.\n\n**4. Protect Against Flood Damage**\n\n* If you live in a flood-prone area, consider purchasing flood insurance to protect your home",
    "---\nTrade Confirmation\n\nTrade Type: Phone\\_Confirmation\n\nDate: March 15, 2023\n\nClient Name: Acme Corp\nClient Contact: John Doe\nBroker: Jane Smith\n\nSecurity Details:\n- Stock: XYZ Inc.\n- Ticker: XYZ\n- CUSIP: 123456789\n\nTrade Details:\n- Trade Date: March 14, 2023\n- Quantity: 5,000 shares\n- Price: $25.00 per share\n- Trade Value: $125,000\n\nSettlement Instructions:\n- Settlement Date: March 20, 2023\n- Delivery Method: DTC\n- Account Number: 123456789\n\nConfirmation Call Script:\n\nBroker: Hi John, this is Jane from the brokerage. I'm calling to confirm the details of your trade executed on March 14, 2023.\n\nClient: Hi Jane, thanks for calling. Please go ahead and confirm the details.\n\nBroker: You purchased 5,000 shares of XYZ Inc. at a price of $25.00 per share. The total value of the trade is $125,000.\n\nClient: That's correct.\n\nBroker: The settlement date for this trade is March 20, 2023. The delivery method will be DTC and the account number is 123456789.\n\nClient: Sounds good, Jane. Thank you for confirming the details.\n\nBroker: You're welcome, John. If you have any questions or concerns, please don't hesitate to contact us. Have a great day!\n\nClient: You too, Jane. Bye.\n\n---",
    'IT Support Ticket #12345\n\n**Category:** File Recovery\n\n**User:** John Doe\n\n**Date:** 01/12/2022\n\n**Problem Description:**\n\nUser reported that they have accidentally deleted an important Word document named "Project Plan v1.docx" from their local system. They urgently need to recover this file.\n\n**Priority:** High\n\n**Status:** In Progress\n\n---\n\n**Temporary Solution:**\n\n1. We recommended the user to stop using the system where the file was deleted to prevent overwriting of the deleted file.\n\n---\n\n**Permanent Solution:**\n\n1. **Data Recovery Software Usage:**\n   - We used EaseUS Data Recovery Wizard (compatible with both Windows and Mac) for this case.\n   - User can download and install the software from the official website: [EaseUS Data Recovery Wizard](https://www.easeus.com/data-recovery-software/).\n\n2. **Selecting Recovery Destination:**\n   - User must connect the system where the file was deleted to the current system using an external hard drive or USB.\n   - In the software, select the external drive as the location for scanning.\n\n3. **Recovering Files:**\n   - Start the scan and wait for the software to complete the scan.\n   - After the scan, select the required file (in this case "Project Plan v1.docx") and click \'Recover\'.\n   - Choose a different location than the one where the file was deleted to avoid overwriting the deleted file.\n\n4. **Restoring Recovered Files:**\n   - After successfully recovering the file, the user must save it in their desired location.\n\n---\n\n**Resolution:**\n\n1. User downloaded and installed the recommended software.\n2. Connected the external hard drive and selected it as the location for scanning.\n3. Ran the scan and recovered the required file.\n4. Saved the recovered file in a different location.\n\n**Status:** Resolved\n\n**Closing Remarks:**\n\nPlease remember to always keep a backup of important files to prevent such scenarios in the future.\n\n**Closed:** 02/12/2122',
    'SECOND MORTGAGE LOAN AGREEMENT\n\nTHIS AGREEMENT is made this ______ day of ________, 20__, by and between _______________ (hereinafter "Lender"), and Adora C. Crespi, of 6384 Steven Orchard Apt. 868, (hereinafter "Borrower").\n\nWHEREAS, Borrower is the owner of certain real property described in Exhibit A attached hereto (hereinafter the "Premises"); and\n\nWHEREAS, Borrower desires to borrow from Lender the sum of _________ dollars ($_______) (hereinafter the "Loan"), and Lender is willing to advance said sum to Borrower upon the terms and conditions hereinafter set forth;\n\nNOW, THEREFORE, in consideration of the mutual covenants contained herein and for other good and valuable consideration, the receipt and sufficiency of which is hereby acknowledged, the parties hereto agree as follows:\n\n1. LOAN. Lender agrees to advance the Loan to Borrower, and Borrower agrees to accept the Loan from Lender, upon the terms and conditions set forth herein.\n\n2. SECURITY. As security for the payment of the Loan, Borrower grants to Lender a second mortgage lien on the Premises, subordinate only to the first mortgage lien now of record against the Premises, if any.\n\n3. REPAYMENT TERMS. The Loan shall be repaid in equal monthly installments of _________ dollars ($_______) commencing on _________, 20__, and continuing on the same day of each month thereafter until the Loan is fully paid.\n\n4. INTEREST RATE. The Loan shall bear interest at the rate of ________ percent (__%) per annum.\n\n5. USE OF PROCEEDS. Borrower acknowledges that the Loan proceeds will be used for the specific equity requirements and potential uses of the loan proceeds as outlined in Exhibit B attached hereto.\n\n6. DEFAULT. In the event of default by Borrower under any of the terms or provisions of this Agreement, Lender shall have the right to declare the entire unpaid balance of the Loan immediately due and',
    "Rehabilitation Services Claim\n\nClaimant Information:\nEmployee ID: Wc-75425\nName: Odette Coulon-Antoine\nStreet Address: 8062 Hensley Mews, South Danastad\n\nPatient Information:\nName: Odette Coulon-Antoine\nDate of Birth: 03/12/1985\nGender: Female\n\nDiagnosis:\nICD-10 Code: S43.021A\nDiagnosis Description: Dislocation of unspecified carpometacarpal joint of left thumb, initial encounter\n\nTreatment Information:\nTherapy Start Date: 02/10/2023\nTherapy End Date: 03/24/2023\nTherapist Information:\nTherapist Name: Dr. Jane Smith\nLicense Number: PT-12345\nTherapy Type: Occupational Therapy\n\nTreatment Details:\nTherapy Session 1: Evaluation and treatment planning\nTherapy Session 2: Manual therapy and exercises for range of motion\nTherapy Session 3: Custom orthotic fitting and education on proper use\nTherapy Session 4-10: Progressive exercises and activities for functional use of left thumb\n\nBilling Information:\nTotal Charges: $1200\nTotal Payments: $800\nBalance Due: $400\n\nI certify that the above information is true and accurate to the best of my knowledge.\n\nSignature: ______________________ Date: _________________\n\nNote: This is a synthetic document and any resemblance to real persons, living or dead, is purely coincidental.",
    "**Partnership Tax Return**\n\n**Tax Year:** 2021\n\n**Partnership Name:** ABC Design Partnership\n\n**Employer Identification Number (EIN):** 12-3456789\n\n**Partnership Agreement:** The partnership agreement for ABC Design Partnership outlines that profits and losses are to be divided equally among the partners. The partners consist of John Doe and Jane Smith.\n\n**Profit and Loss Statement:**\n\n* Gross Receipts: $500,000\n* Returns and Allowances: $15,000\n* Net Gross Receipts: $485,000\n* Cost of Goods Sold: $250,000\n* Gross Profit: $235,000\n* Salaries and Wages: $100,000\n* Rent Expense: $30,000\n* Utilities: $15,000\n* Supplies: $20,000\n* Depreciation: $25,000\n* Total Expenses: $190,000\n* Net Income: $45,000\n\n**Balance Sheet:**\n\n* Assets:\n\t+ Cash: $25,000\n\t+ Accounts Receivable: $50,000\n\t+ Inventory: $150,000\n\t+ Property, Plant, and Equipment: $200,000\n\t+ Total Assets: $425,000\n* Liabilities:\n\t+ Accounts Payable: $30,000\n\t+ Accrued Expenses: $10,000\n\t+ Total Liabilities: $40,000\n* Equity:\n\t+ Partner 1, John Doe: $207,500\n\t+ Partner 2, Jane Smith: $207,500\n\t+ Total Equity: $415,000\n\n**Form 1065, U.S. Return of Partnership Income:**\n\n* Line 1: Total income, gross receipts, or gains",
    '<?xml version="1.0" encoding="UTF-8"?>\n<financial-data-feed>\n  <exchange-traded-funds>\n    <etf>\n      <employee-id>Rx-25098</employee-id>\n      <name>Natalie Vargas</name>\n      <ticker-symbol>NVFund</ticker-symbol>\n      <composition>\n        <instrument>\n          <ticker-symbol>AAPL</ticker-symbol>\n          <weight>0.25</weight>\n        </instrument>\n        <instrument>\n          <ticker-symbol>GOOGL</ticker-symbol>\n          <weight>0.20</weight>\n        </instrument>\n        <instrument>\n          <ticker-symbol>MSFT</ticker-symbol>\n          <weight>0.15</weight>\n        </instrument>\n      </composition>\n      <net-asset-value>125.67</net-asset-value>\n      <trading-volume>56789</trading-volume>\n    </etf>\n  </exchange-traded-funds>\n  <market-data>\n    <market-price>\n      <ticker-symbol>NVFund</ticker-symbol>\n      <price>45.67</price>\n    </market-price>\n  </market-data>\n</financial-data-feed>',
    "Venmo Transfer Confirmation\n\nTransaction ID: 4567ghd890jklo123\nAmount: £50.00 GBP\nPayer: John Smith\nPayee: Sarah Jones\nTimestamp: 2022-03-14 16:35:28 GMT\n\nThank you for using Venmo!\n\nNote: This is a synthetic record created for demonstration purposes and does not represent a real financial transaction.",
    "Sure, here's an example of a credit card statement for a Transaction Trends analysis:\n\nCredit Card Statement\nAccount Holder: John Doe\nAccount Number: 1234-5678-9012-3456\nStatement Period: 01/01/2023 - 01/31/2023\n\nTransaction Summary:\nTotal Transactions: 15\nTotal Spent: $2,547.89\nAverage Spent per Transaction: $169.86\n\nTop Merchants:\n\n1. Amazon - $456.35 (4 transactions)\n2. Starbucks - $214.50 (5 transactions)\n3. Uber - $195.20 (3 transactions)\n4. Whole Foods - $187.55 (2 transactions)\n5. Apple - $155.00 (1 transaction)\n\nSpending Trends:\n- Peak spending days: Tuesdays and Fridays\n- Average spent on weekdays: $112.54\n- Average spent on weekends: $141.32\n- Largest transaction: $456.35 (Amazon)\n- Smallest transaction: $5.00 (Starbucks)\n\nPayment Information:\nDue Date: 02/25/2023\nMinimum Payment: $50.00\nLate Fee: $35.00 (if payment not received by due date)\n\nPlease note that this is a fictional statement and any resemblance to real persons, living or dead, or actual events, is purely coincidental.",
    "Title: Server Overload on Sales Database Server\n\nID: SER-2023-0012\n\nDate Created: 2023-03-15 10:30:00\n\nPriority: High\n\nStatus: In Progress\n\nAssigned To: John Doe (IT Operations)\n\n**Problem Description:**\n\nOn 2023-03-15 at approximately 10:00 GMT, the sales database server (server-sales-01.example.com) started experiencing performance issues. Users reported slow response times and timeouts when accessing the sales application. The server load has been consistently above 80% for the past hour.\n\n**Steps Taken:**\n\n1. Verified the server load using the `uptime` command.\n2. Checked running processes and identified several resource-intensive queries on the sales database.\n3. Examined the disk space and found that it is currently at 85% capacity.\n\n**Troubleshooting:**\n\n1. Stopped unnecessary services on the server to free up resources.\n2. Optimized the identified resource-intensive queries.\n3. Cleared the database logs to free up disk space.\n\n**Current Situation:**\n\nThe server load has decreased to around 60%, but still higher than the normal level. The disk space is still at 85% capacity.\n\n**Next Steps:**\n\n1. Investigate the possibility of upgrading the server hardware (specifically, adding more RAM and increasing the disk space).\n2. Review the current resource allocation and usage patterns on the server.\n3. Consider implementing a load balancer to distribute the load across multiple servers.\n\n**Resolution Details:**\n\nTo be updated.\n\n**Additional Notes:**\n\nThe sales application is critical for the business operations, and any further degradation in performance may impact the sales revenue. Immediate action is required to resolve the issue and prevent any recurrence.",
    'FREELANCE AGREEMENT\n\nThis Freelance Agreement (the "Agreement") is entered into as of the date of acceptance by the Freelancer, by and between [Company Name], a company organized and existing under the laws of [State/Province], with its head office located at [Company Address] (the "Company"), and Katherine Rogers, an individual with a mailing address of 48354 Shelton Heights Apt. 089 (the "Freelancer").\n\n1. Services\n\nThe Freelancer agrees to provide the services (the "Services") as described in Exhibit A attached hereto.\n\n2. Term\n\nThe term of this Agreement shall commence on [Start Date] and shall continue until the completion of the Services, unless otherwise terminated in accordance with this Agreement.\n\n3. Compensation\n\nThe Company shall pay the Freelancer a total of [Amount] for the completion of the Services, payable in accordance with the payment schedule set forth in Exhibit A attached hereto.\n\n4. Expenses\n\nThe Freelancer shall be responsible for all expenses incurred in the performance of the Services, including, but not limited to, travel, meals, and supplies.\n\n5. Confidentiality\n\nThe Freelancer agrees to keep confidential all non-public information concerning the Company that the Freelancer learns during the course of performing the Services, and to not disclose such information to any third party without the prior written consent of the Company.\n\n6. Termination\n\nEither party may terminate this Agreement upon providing written notice to the other party if the other party breaches any material term or condition of this Agreement and fails to cure such breach within [Cure Period].\n\n7. Governing Law\n\nThis Agreement shall be governed by and construed in accordance with the laws of [State/Province], without regard to its conflict of laws principles.\n\n8. Entire Agreement\n\nThis Agreement constitutes the entire agreement between the parties and supersedes all prior or contemporaneous agreements or understandings, whether written or oral, relating to the subject matter of this Agreement.\n\nIN WITNESS WHEREOF, the parties have executed this Freelance Agreement as of the date first above written.\n\n[Company Name]\n\nBy: __________________________\n[Company Name',
    "Health Insurance Claim Form\n\nClaimant Information:\nName: Monica Sjöberg\nAddress: 757 Recep-Kreusel-Allee, 71381, Plauen\nPolicy Number: TURPIN79-001\n\nType of Claim: Specialist Consultation\n\nSpecialist Information:\nName: Dr. Smith\nSpecialty: Cardiology\nCredentials: MBBS, MRCP, FESC\nReason for Visit: Follow-up consultation for heart condition\n\nHealthcare Provider Information:\nName: St. Mary's Hospital\nAddress: Cardiology Department, Queen's Gate, London, SW7 5AA\n\nTreatment Details:\nDate of Consultation: 12th March, 2023\nTreatment Received: Specialist consultation and ECG\nCost of Treatment: £350\n\nDeclaration:\nI, Monica Sjöberg, confirm that the above information is true and accurate to the best of my knowledge. I understand that providing false or misleading information may result in the rejection of this claim and/or future claims.\n\nSignature: Monica Sjöberg\nDate: 15th March, 2023",
    "Payment Confirmation\n\nPayee Information:\nName: John Doe\nAddress: 123 Maple Street\nCity: Toronto\nPostal Code: M5J 1K5\n\nPayer Information:\nName: ABC Corporation\nAddress: 456 Elm Street\nCity: Toronto\nPostal Code: M5H 2L7\n\nPayment Type: Payroll Deposit\n\nTransaction Details:\nAmount: CAD 3,500.00\nDate of Transaction: November 30, 2021\n\nAdditional Information:\nThis payment confirmation serves as proof of the successful initiation of a payroll deposit for the above-mentioned amount. Please ensure that the payer has accurately recorded the deposit details for future pay cycles.\n\nThank you for choosing ABC Corporation for your payroll needs. If you have any questions or concerns, please do not hesitate to contact us at [payroll@abccorp.com](mailto:payroll@abccorp.com) or 1-800-123-4567.\n\nSincerely,\n\n[Your Name]\nPayroll Administrator\nABC Corporation",
]

for text in texts:
    try:
        entities = extract_entities(text=text)
        print(entities)
    except Exception as e:
        print(text, e)
        continue
